#!/usr/bin/env php
<?php
if ($argc !== 2) {
    die('missing function name');
}

$functionsHash = json_decode(file_get_contents(__DIR__."/../projects/php_function_list"), true);
$functionName = $argv[1];

$output = "";
if (isset($functionsHash[$functionName])) {
    $offset = 0;
    foreach($functionsHash[$functionName] as $functionInfo) {
        $offset ++;
        $output .= "$offset {$functionInfo[0]}($functionInfo[1]) $functionName\n";
    }
}
print $output;
